# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#   // Спасибо, что скачали мой античит
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

# - - - - - -> ОСНОВНОЕ <- - - - - -
# punishment - ваша команда наказания, заполнитель
# violations - количесво нарушений до наказания игрока
# enable - включить/выключить проверку, enable: true - включить, enable: false - выключить

# - - - - - -> Заполнители <- - - - - -
# %player% - вывод ника игрока


Checks:
  # Проверки на ротацию (Aim, KillAura)
  Aim:
    # Хорошо обнаруживает большинсво киллаур, в том числе и Nursultan, за 2-3 минуты
    # Я сделал так, что каждый может настроить и переписать полностью проверку
    # Пожалуйста, поделитесь своей настройкой, если вам удалось сделать наилучший
    # результат без ложных срабатываний, в Discord: gotsDaniil
    a:
      enable: true
      violations: 1
      punishment: kick %player% &cAC Вы были кикнуты за подозрение в читах (AimA)
      Settings:
        Speed: 1.7561319565173843E-9 # Минимальная скорость передвижения, можно запутаться в трюке с E-9 и E-10
        minAtan2: 0.1 # Минимальный арктангенс
        maxAtan2: 1 # Максимальный арктангенс
        minAccuracy: 0.13 # Минимальное отклонение точности (высчитывает от 0 градусов)
        maxAccuracy: 0.5 # Максимальное отклонение точности
        minRotationSinCos: 0.76 # Минимальный порог ротации в Sin и Cos
        maxRotationSinCos: 0.95 # Максимальный порог ротации в Sin и Cos
        minDirectionChange: 0.2 # Минимальная скорость ротации
        maxDirectionChange: 0.5 # Максимальная скорость ротации
        minDirectionChangeSpeed: 0.5 # Минимальное изменение направления
        maxDirectionChangeSpeed: 1 # Максимальное изменение направления
        minRotationSpeed: 2 # Минимальная скорость ротации с Yaw и Pitch
        maxRotationSpeed: 3 # Максимальная скорость ротации с Yaw и Pitch
      AddChecks:
        # Включить/выключить дополнительные параметры, добавляется к предыдушим параметрам
        enable: false
        minSnapAim: 0.1 # Минимальное значение считаемое резким (Снапы)
        maxSnapAim: 1 # Максимальное значение считаемое резким (Снапы)
        minSilentDeviation: 0.8 # Минимальное отклонение ротации в соответствии с движением
        maxSilentDeviation: 2 # Максимальное отклонение ротации в соответствии с движением
        minAngleDelta: 0.2 # Минимальное изменение угла между Yaw и Pitch
        maxAngleDelta: 2 # Максимальное изменение угла между Yaw и Pitch
    # Проверка на ротацию при походе через игрока, видит некоторые киллауры
    b:
      enable: true
      violations: 1
      punishment: kick %player% &cAC Вы были кикнуты за подозрение в читах (AimB)
      Settings:
        minAtan2: 1.43 # Минимальный арктангенс
        maxAtan2: 1.7 # Максимальный арктангенс
        minAccuracy: 0.22 # Минимальное отклонение точности (высчитывает от 0 градусов)
        maxAccuracy: 0.38 # Максимальное отклонение точности
        minDirectionChange: 0.38 # Минимальная скорость ротации
        maxDirectionChange: 0.45 # Максимальная скорость ротации
  # Проверка на AutoFish (авто-рыбалку)
  AutoFish:
    a:
      enable: true
      violations: 1
      punishment: 'kick %player% &cAC Вы были кикнуты за подозрение в читах (AutoFish)'
      deviation: 1.5 # Отклонение удочки, лучше не менять
    b:
      enable: true
      punishment: 'kick %player% &cAC Вы были кикнуты за подозрение в читах (AutoFish)'
      time: 1800000 # Время в секундах через которое кикнет за АФК
  # Проверка на атаку во время еды
  AttackEat:
    a:
      enable: true
  # Блокировка выхода за верхний бедрок в аду
  AdHeightFix:
    a:
      enable: true
      height: 126 # Ваша высота уровня верхнего бедрока
      teleport: 122 # Телепортируем игрока на эту высоту
      message: 'Вы неможете выходить за бедрок' # Отправка сообщения
  # Баним игрока за определенные сообщения в чате
  ChatBan:
    a:
      enable: true
      punishment: 'tempipban %player% 14d &cAC Вы были временно забанены подозрение в читах'
  # Блокируем игроков с никами читов, некоторых крашеров и ботов
  NicknameBans:
    a:
      enable: true
      punishment: 'banip %player% &cAC Вы были временно забанены подозрение в читах'
  # Проверка на быстрый флай
  DragonFly:
    a:
      enable: true
      punishment: 'kick %player% &cAC Вы были кикнуты за подозрение в читах (DragonFly)'
      violations: 350
      Settings:
        Speed_1_zx: 22.5 # Скорость по X и Z, для 10 скоростей в /flyspeed
        Speed_2_zx: 45.5
        Speed_3_zx: 65.5
        Speed_4_zx: 88.5
        Speed_5_zx: 110.5
        Speed_6_zx: 132.5
        Speed_7_zx: 146.5
        Speed_8_zx: 173.5
        Speed_9_zx: 178.5
        Speed_10_zx: 217.5
        Speed_1_y: 56 # Скорость по Y, для 10 скоростей в /flyspeed (проверяет только на высокой скорости)
        Speed_2_y: 56
        Speed_3_y: 56
        Speed_4_y: 56
        Speed_5_y: 56
        Speed_6_y: 66
        Speed_7_y: 76
        Speed_8_y: 86
        Speed_9_y: 96
        Speed_10_y: 106
  # Проверка на флай с элитрой, только по Y
  ElytraFly:
    a:
      enable: true
      punishment: 'kick %player% &cAC Вы были кикнуты за подозрение в читах (ElytraFly)'
      violations: 350
      height: 4.5 # Высота при которой происходит флаг
  # Блокируем быстрое использование пузырьков опыта
  FastExp:
    a:
      enable: true
  # Блокирует эксплоит с получением креатива
  GamemodeCreativeFix:
    a:
      enable: true